[dependencies]
base = "0.9.8"
array = "https://github.com/aviate-labs/array.mo#v0.1.1"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.3.1"
cap = "https://github.com/stephenandrews/cap-motoko-library#v1.0.4-alt"